[package]
name = "r_place_data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0"
chrono = "0.4"
regex = "1.5"
lazy_static = "1.4.0"